[line_break]
disabled = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = true
show_always = true

[hostname]
ssh_only = false
format =  "[ğŸ¥·](bold #AEC3AE) " # [$hostname]
trim_at = ".fritz.box"
disabled = false

[character]
success_symbol = "[ó°’ ](bold #F0CAA3) "
error_symbol = "[ï€](bold red) "

[cmd_duration]
min_time = 60_0000


[gcloud]
disabled = true
